### ISSUE TITLE
Support async Dapper methods, e.g. QueryAsync

### ISSUE THREAD

**Issue by tjrobinson** [UnoSD/Moq.Dapper#5]
Hopefully the title is self explanatory. When using Moq.Dapper with QueryAsync an exception is thrown as it's not supported.

I have had a go at creating a PR for this but without much luck.

If you can give me an idea as to how you would approach it I can have another go.

**Comment by UnoSD** [comment]
Hi @tjrobinson, I just had a look and `QueryAsync` is a bit trickier as it (surprise, surprise) expects the `IDbCommand` to be a `DbCommand` and does downcasting internally.

If you want to have a go, you will have to mock a `DbCommand` instead of an `IDbCommand`.

`DbCommand` has, for instance, `ExecuteDbDataReaderAsync` as a virtual method called by Dapper that you can easily mock to return the same reader from the sync version and wrap it into a `Task`.

I won't have much time this weekend again otherwise I would have drafted an implementation myself. But I hope I will get to it at some point. Feel free to have a go and to ask me questions if you get stuck if you don't want to wait.

**Comment by tjrobinson** [comment]
@UnoSD Thanks, I'm not sure when I'll get a chance to have a go but if I do come up with anything I'll leave a comment here.

**Comment by rolingjp** [comment]
I would also like to see this, but I was unable to get it working.  Any updates / suggestions?

**Comment by UnoSD** [comment]
Unfortunately I couldn't find some spare time to look into this, but I wrote already some hint from a brief investigation in my reply above. Feel free to ask me questions here and I will try and help when I can.

**Comment by UnoSD** [comment]
Quick update, I had some spare time at lunch today and I think I managed to mock `QueryAsync` I'll clean it up and push it hopefully in the afternoon or just push a "to clean up" branch for you to have a look.

**Comment by UnoSD** [comment]
OK, it needs some tidying up as it's mostly a copy and paste of the sync code, but it's there and I'm going to push it for you guys to have a look and play with. I hope I will have time to refactor it.

**Comment by rolingjp** [comment]
Very cool!  Thanks.
